Fix for #1528, setup ObjectMapper configuration for DgsWebSocketAutoC…
Netflix/dgs-framework pull request #1602
Opened 2023-08-16 22:42 UTC by clayembry

Fix for #1528, setup ObjectMapper configuration for DgsWebSocketAutoConfig to mirror DgsWebMvcAutoConfiguration.

Pull request checklist
----

- [x] Please read our [contributor guide](https://github.com/Netflix/dgs-framework/blob/master/CONTRIBUTING.md)
- [x] Consider creating a discussion on the [discussion forum](https://github.com/Netflix/dgs-framework/discussions)
  first
- [x] Make sure the PR doesn't introduce backward compatibility issues
- [x] Make sure to have sufficient test cases

Pull Request type
----

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----

Issue #1528

The ObjectMappers in `WebsocketGraphQLTransportWSProtocolHandler` and `WebsocketGraphQLWSProtocolHandler` have been refactored for constructor injection instead of having each class instantiate its own ObjectMapper in a companion object. This fixes an immediate problem we are having where our subscriptions fail with errors because the subscription ObjectMappers do not have JSR310 time module configured. In addition, `DgsWebSocketAutoConfig` has been configured to create a Qualified ObjectMapper named "dgsObjectMapper" if it has not already been created.

My previous Kotlin and Gradle experience is limited, so I just followed the patterns for how ObjectMapper is used and configured in `DgsRestController` and `DgsWebMvcAutoConfiguration`. This PR establishes uniform ObjectMapper usage for graphql requests and subscriptions.

Alternatives considered
----

I could have added the JSR310 time module to the companion object ObjectMappers in `WebsocketGraphQLTransportWSProtocolHandler` and `WebsocketGraphQLWSProtocolHandler`. But then what happens the next time a change is needed to ObjectMapper configuration. It would have to be changed in many places instead of just updating the "dgsObjectMapper" config.

2023-08-17 22:38 UTC, srinivasankavitha requested changes
Thanks for the PR! The changes look good, have a few suggestions.

2023-08-17 22:38 UTC, srinivasankavitha commented on graphql-dgs-subscriptions-websockets-autoconfigure/src/test/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/autoconfigure/DgsWebSocketAutoConfigTest.kt
> + * Copyright 2023 Netflix, Inc.
You won't need this test once you get rid of the object mapper bean.

2023-08-18 18:26 UTC, clayembry commented on graphql-dgs-subscriptions-websockets-autoconfigure/src/main/kotlin/com/netflix/graphql/dgs/subscriptions/websockets/DgsWebSocketAutoConfig.kt
>      @Bean
Yeah, I was thinking if someone was only using the subscription starter by itself. But probably that's not possible.

I'll remove the unnecessary bean config.

2023-08-21 17:52 UTC, srinivasankavitha commented
You can fix lint failure by running `./gradlew formatKotlin`

2023-08-21 20:14 UTC, srinivasankavitha approved these changes

2023-08-21 20:14 UTC, merged