Fix handling of @InputArgument for Java objects with optionals.
Netflix/dgs-framework pull request #1926
Opened 2024-05-27 23:12 UTC by srinivasankavitha

Pull Request type
----

- [x] Bugfix
- [ ] Feature
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Other (please describe):

Changes in this PR
----
This PR fixes handling of @InputArgument for optionals. The current implementation of the DefaultInputObjectMapper does not handling converting from map to optionals, resulting in the following error when used: 
```
**Failed to convert from type [java.util.LinkedHashMap<?, ?>] to type [@com.netflix.graphql.dgs.InputArgument 
```
Conversion of String to Optional<String>, for e.g works fine since Spring's `ObjectToOptionalConverter` handles this fine: https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/convert/support/ObjectToOptionalConverter.java

Adding similar logic to the `DefaultInputObjectMapper` to handle optionals based on this code: https://github.com/spring-projects/spring-framework/blob/main/spring-core/src/main/java/org/springframework/core/convert/support/ObjectToOptionalConverter.java#L76

_Describe the new behavior from this PR, and why it's needed_
Issue #1925

2024-05-28 17:49 UTC, Emily requested changes
Could you add a test that checks the behavior when one of the optional fields isn't present?

2024-05-28 21:23 UTC, paulbakker commented on graphql-dgs/src/main/kotlin/com/netflix/graphql/dgs/internal/DefaultInputObjectMapper.kt
> +            if (targetType.resolvableType.hasGenerics()) {
Should this check specifically for `Optional` instead of any type with generics?

2024-06-27 09:56 UTC, filippocozzini commented
Any update?

2024-06-27 16:50 UTC, srinivasankavitha commented
> Any update?

Sorry for the delay. I need to address some of the comments before I can push the fix through.

2024-06-27 19:49 UTC, srinivasankavitha commented
Declining this PR in favor of a better fix here: https://github.com/Netflix/dgs-framework/pull/1951

2024-06-27 19:49 UTC, closed without merging